### ISSUE TITLE
실행방법 정리

### ISSUE THREAD

**Issue by KJunseo** [KJunseo/Traveler-Club-Mileage-Service#12]
### Description
실행 방법 정리
- http 파일 활용?

### Todo
- [x] 실행 과정 설정
- [x] 실행 과정 readme에 정리
- [x] docker compose m1처리 부분 명시
