### ISSUE TITLE
더미 데이터 넣기

### ISSUE THREAD

**Issue by KJunseo** [KJunseo/Traveler-Club-Mileage-Service#4]
### Description
리뷰 작성 이벤트 API를 수행하기 위해 필요한 더미데이터를 삽입한다.

### Todo
- [x] User 더미 데이터 삽입
- [x] Place 더미 데이터 삽입
- [x] Photo 더미 데이터 삽입
- [x] Review 더미 데이터 삽입
