### ISSUE TITLE
포인트 적립 API 구현 - 2 (리뷰 수정시 발생)

### ISSUE THREAD

**Issue by KJunseo** [KJunseo/Traveler-Club-Mileage-Service#8]
### Description
- 리뷰 수정시 발생하는 포인트 적립 API 구현하기
  - 포인트가 증감할때마다 이력을 남겨야한다.

- request(POST /events)
  - type: "REVIEW"(리뷰 작성 이벤트인 경우)
  - action
    - "MOD": 리뷰 수정시
      - 기존 리뷰로 부여받았던 포인트 감소시키기
      - 새로운 리뷰(content)로 부여받을 포인트 증가시키기 
  - reviewId: 관련 리뷰 ID
  - content: 관련 리뷰 내용
  - attachedPhotoIds: 관련 리뷰에 포함된 사진들
  - userId: 관련 리뷰 작성자 ID
  - placeId: 관련 리뷰가 작성된 장소 ID

- response
  - 200
  - no content

### Todo
- [ ] 포인트 적립 API 구현
- [ ] 포인트 증감 이력 남기기
- [ ] 테스트 코드 작성
- [ ] API 문서화
